import type { Metadata } from "next";
import { Noto_Sans_TC } from "next/font/google";
import localFont from "next/font/local";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import Navbar from "./components/Navbar";

const notoSansTC = Noto_Sans_TC({
  variable: "--font-noto-sans-tc",
  subsets: ["latin"],
});

const sourceHanSerifTC = localFont({
  src: "../public/fonts/SourceHanSerifTC-Bold.otf",
  variable: "--font-source-han-serif-tc",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="zh-Hant-TW">
      <body
        className={`${notoSansTC.variable} ${sourceHanSerifTC.variable} antialiased text-base sm:text-lg leading-relaxed`}
      >
        <ThemeProvider attribute="class">
          <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
            <Navbar />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
